title: Tiziano Rotesi
logo: /assets/img/rotesi3.jpg
description: |
  I am Post-Doctoral Fellow in Economics at UNIL. 
  My area of research is Applied Microeconomics and Experimental Economics, with a focus on Empirical Political Economy and the Economics of Networks.  
show_downloads: false
google_analytics: UA-125020658-1
theme: jekyll-theme-minimal
