title: Tiziano Rotesi
logo: /assets/img/pic.jpg
description: |
  I am a <b>PhD Candidate in Economics</b> at <b>Bocconi University</b>. 
  My area of reasearch is <b>Applied Microeconomics</b>, with a focus on <b>Empirical Political Economy</b> and the <b>Economics of Networks</b>.  
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
