title: Tiziano Rotesi
logo: /assets/img/pic.jpg
description: |
  I am a PhD Candidate in Economics at Bocconi University. 
  I am working on topics related to political economy, networks. Broad interests concern applied microeconomics.  
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
