title: Tiziano Rotesi
logo: /assets/img/pic.jpg
description: |
  I am a PhD Candidate in Economics at Bocconi University. 
  My area of reasearch is Applied Microeconomics, with a focus on Empirical Political Economy and the Economics of Networks.  
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
